[sc-28766] Adds firstValid
flipstone/redcard pull request #20
Opened 2023-02-10 19:53 UTC by AugmenTab

This adds a function `firstValid` that can be used to chain validations together in a manner not dissimilar to `Alternative`. It will run each validator in turn until it comes to one with a valid result, or finally invalidate.

2023-02-12 13:39 UTC, jbrechtel requested changes
What's up with the stack yaml addition? Redcard has LTS specific stack yaml files already. Adding a new one is fine but it'd be nice for it to follow the existing convention.

2023-02-12 13:50 UTC, jbrechtel commented
Also, now that I see your usage of this you might want to consider a 'NE.NonEmpty Validator' version of this so you don't have to chain firstValid so much

2023-02-13 13:54 UTC, AugmenTab commented
> Also, now that I see your usage of this you might want to consider a 'NE.NonEmpty Validator' version of this so you don't have to chain firstValid so much

Is something like `foldUntilValid` from [`269df06`](https://github.com/flipstone/redcard/pull/20/commits/269df06b20d726161b575d75392eb81475eff9af) what you had in mind?

2023-02-13 16:49 UTC, exodrifter approved these changes

2023-02-13 16:50 UTC, merged